# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c2687838fe253029d1bf7d552c50d81c2b7bd1b92e1665a179f5aff0614e12defcb64e759ff08969bb642713bf6da3b0722ce7ee545e82f0c2323d43ad55fe8

test:
  secret_key_base: 9a7009d6d94514bdae9000e60135cf513878830a48c60a4c84e9df7645b1175c435b735666e42e0074ff8074720f588c7e7ce57fe593bcf6b395c3638c43f507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
